export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as PourquoiSpins } from './PourquoiSpins'
export { default as Equipe } from './Equipe'
export { default as FAQ } from './FAQ'
export { default as Footer } from './Footer'
